services:
  rebot:
    image: ghcr.io/repryty/rebot-8:main
    pull_policy: always
    container_name: rebot-8
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./images:/app/images
      - ./log:/app/log